### ISSUE TITLE
Update Dependency Information 

### ISSUE THREAD

**Issue by nayomaise** [P03W/ServShred#13]
With the quilt rewrite it would be nice to add info to Modrinth and CursedForge (and the README) about the new dependencies right now it only likes Fabric Kotlin

**Comment by SilverAndro** [comment]
I dont maintain my curseforge pages anymore, and its already updated on modrinth

![image](https://github.com/SilverAndro/ServShred/assets/52360088/b2914e76-8026-48d9-9cf9-d9b73f65b9b4)

Ive updated the github about to say "Serverside veinminer for quilt"
