### ISSUE TITLE
1.18.1 Version

### ISSUE THREAD

**Issue by di3d** [P03W/ServShred#3]
Hi, will there be a 1.18.1 version for this? Thank you very much!

**Comment by SilverAndro** [comment]
Got a crash report or bug?

**Comment by di3d** [comment]
[Pterodactyl Console Log.txt](https://github.com/P03W/ServShred/files/7708896/Pterodactyl.Console.Log.txt)

Not quite a crash report, but this is what my console spits out as my server does not generate a crash report.

**Comment by leo60228** [comment]
It *seems* to work with a dependency override but I haven't fully tested:
```json
{
  "version": 1,
  "overrides": {
    "servshred": {
      "-depends": {
        "minecraft": "IGNORED"
      }
    }
  }
}
```

**Comment by di3d** [comment]
Just tested and added a **fabric_loader_dependencies.json** inside the **config** folder with the dependency override as @leo60228  has stated. 
Mod works pretty much now. Thanks! I guess the mod just needs a small update to the version number.

**Comment by SilverAndro** [comment]
Yep ill be trying to get that out tonight or tomorrow, shouldn't need any updates once I fix that luckily

**Comment by SilverAndro** [comment]
Uploaded to both platforms
