### ISSUE TITLE
Veinminer doesn't apply on Quartz ore blocks & Standard and Deepslate ore block variants can't be veinmined together

### ISSUE THREAD

**Issue by SentySent** [P03W/ServShred#4]
Just like the title, the veinminer effect doesn't apply on Quartz ore blocks.  I tried to but couldn't find a config file or JSON file to include the Quartz blocks and block tags.

Plus both standard and Deepslate ore block variants can't be veinmined together, they have to be mined separately.

**Comment by SilverAndro** [comment]
Well quartz is an easy fix, thanks for pointing that out, not sure how to go about doing the variants together

realistically I think the best I could do is add a "chain blocks" config option that lets a veinmine also mine any other veinminable ones

**Comment by SilverAndro** [comment]
Quartz is now added by default

**Comment by SilverAndro** [comment]
> I tried to but couldn't find a config file or JSON file to include the Quartz blocks and block tags.

Just noticed this, there's a tag under `assets` you can add to like any other block tag

**Comment by SilverAndro** [comment]
> realistically I think the best I could do is add a "chain blocks" config option that lets a veinmine also mine any other veinminable ones

Implemented in 1.0.7
