### ISSUE TITLE
Docs on adding additional blocks to ServShred

### ISSUE THREAD

**Issue by WardsParadox** [P03W/ServShred#8]
Heyo!
Struggling a little bit getting this datapack addition to work and add more ores to ServShred. I can''t seem to get the AE2 or industrial revolution ores to work with ServShred. I was wondering if you could provide some more documentation on how to correctly add ores to ServShred (maybe an example datapack?)

[ServShred_Ores.zip](https://github.com/SilverAndro/ServShred/files/9660282/ServShred_Ores.zip)

**Comment by WardsParadox** [comment]
Disregard, I got it working immediately after opening this 🤦🏻 


Too anyone else looking for help:

Create the following directory and folder structure:
world/datapacks/additional_blocks_for_servshred/data/servshred/tags/blocks/veinmine.json

Add the following JSON in veinmine.json:
```json
{
    "replace": false,
    "values": [
        "create:zinc_ore",
        "create:deepslate_zinc_ore",
        "indrev:tungsten_ore",
        "indrev:tin_ore",
        "indrev:silver_ore",
        "indrev:nikolite_ore",
        "indrev:lead_ore",
        "indrev:tungsten_ore",
        "indrev:tin_ore",
        "indrev:silver_ore",
        "indrev:nikolite_ore",
        "indrev:lead_ore",
        "indrev:deepslate_tungsten_ore",
        "indrev:deepslate_tin_ore",
        "indrev:deepslate_silver_ore",
        "indrev:deepslate_nikolite_ore",
        "indrev:deepslate_lead_ore",
        "indrev:deepslate_tungsten_ore",
        "indrev:deepslate_tin_ore",
        "indrev:deepslate_silver_ore",
        "indrev:deepslate_nikolite_ore",
        "indrev:deepslate_lead_ore",
        "ae2:quartz_ore",
        "ae2:deepslate_quartz_ore"
    ]
}
```

Add a pack.mcmeta in the world/datapacks/additional_blocks_for_servshred directory with:
```json
{
  "pack": {
    "pack_format": 9,
    "description": "Adds more ores to servshred"
  }
}

```

**Comment by WardsParadox** [comment]
[Additional_blocks_for_servshred.zip](https://github.com/SilverAndro/ServShred/files/9660317/Additional_blocks_for_servshred.zip)

And here's a zip of the working datapack

**Comment by SilverAndro** [comment]
Haha happens to everyone
Glad you were able to figure it out!
